# Generated by Django 4.0.1 on 2022-02-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='room_no',
            field=models.CharField(max_length=50),
        ),
    ]
