# Generated by Django 4.0.1 on 2022-02-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_students_room_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students',
        ),
    ]
