# Generated by Django 4.0.1 on 2022-02-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
            ],
        ),
    ]
