# Generated by Django 4.0.1 on 2022-02-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
