# Generated by Django 4.0.1 on 2022-02-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_employe_address_alter_employe_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='question',
            new_name='name',
        ),
    ]
