# Generated by Django 4.0.1 on 2022-02-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_question_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
